package net.gecko.varanarmor.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataGenerator;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.gecko.varanarmor.item.ArmoryItems;
import net.gecko.varanarmor.util.ArmoryTags;
import net.minecraft.item.Items;
import net.minecraft.tag.ItemTags;

public class ArmoryItemTagProvider extends FabricTagProvider.ItemTagProvider {
    public ArmoryItemTagProvider(FabricDataGenerator dataGenerator) {
        super(dataGenerator);
    }

    @Override
    protected void generateTags() {
        getOrCreateTagBuilder(ItemTags.ARROWS)
                .add(ArmoryItems.IRON_ARROW)
                .add(ArmoryItems.AMETHYST_ARROW)
                .add(ArmoryItems.QUARTZ_ARROW)
                .add(ArmoryItems.NETHER_ARROW);

    getOrCreateTagBuilder(ArmoryTags.Items.HARVESTERS)
            .addTag(ArmoryTags.Items.SICKLES)
            .addTag(ArmoryTags.Items.HOES);

        getOrCreateTagBuilder(ArmoryTags.Items.AXES)
                .addTag(ArmoryTags.Items.SINGLE_AXES)
                .addTag(ArmoryTags.Items.DOUBLE_AXES);

    getOrCreateTagBuilder(ArmoryTags.Items.SICKLES)
            .add(ArmoryItems.WOODEN_SICKLE)
            .add(ArmoryItems.FLINT_WOODEN_SICKLE)
            .add(ArmoryItems.LAPIS_WOODEN_SICKLE)
            .add(ArmoryItems.QUARTZ_WOODEN_SICKLE)
            .add(ArmoryItems.STONE_SICKLE)
            .add(ArmoryItems.FLINT_STONE_SICKLE)
            .add(ArmoryItems.LAPIS_STONE_SICKLE)
            .add(ArmoryItems.QUARTZ_STONE_SICKLE)
            .add(ArmoryItems.IRON_SICKLE)
            .add(ArmoryItems.FLINT_IRON_SICKLE)
            .add(ArmoryItems.LAPIS_IRON_SICKLE)
            .add(ArmoryItems.QUARTZ_IRON_SICKLE)
            .add(ArmoryItems.GOLDEN_SICKLE)
            .add(ArmoryItems.FLINT_GOLDEN_SICKLE)
            .add(ArmoryItems.LAPIS_GOLDEN_SICKLE)
            .add(ArmoryItems.QUARTZ_GOLDEN_SICKLE)
            .add(ArmoryItems.DIAMOND_SICKLE)
            .add(ArmoryItems.FLINT_DIAMOND_SICKLE)
            .add(ArmoryItems.LAPIS_DIAMOND_SICKLE)
            .add(ArmoryItems.QUARTZ_DIAMOND_SICKLE)
            .add(ArmoryItems.NETHERITE_SICKLE)
            .add(ArmoryItems.FLINT_NETHERITE_SICKLE)
            .add(ArmoryItems.LAPIS_NETHERITE_SICKLE)
            .add(ArmoryItems.QUARTZ_NETHERITE_SICKLE);

        getOrCreateTagBuilder(ArmoryTags.Items.CLAYMORES)
                .add(ArmoryItems.WOODEN_CLAYMORE)
                .add(ArmoryItems.FLINT_WOODEN_CLAYMORE)
                .add(ArmoryItems.LAPIS_WOODEN_CLAYMORE)
                .add(ArmoryItems.QUARTZ_WOODEN_CLAYMORE)
                .add(ArmoryItems.STONE_CLAYMORE)
                .add(ArmoryItems.FLINT_STONE_CLAYMORE)
                .add(ArmoryItems.LAPIS_STONE_CLAYMORE)
                .add(ArmoryItems.QUARTZ_STONE_CLAYMORE)
                .add(ArmoryItems.IRON_CLAYMORE)
                .add(ArmoryItems.FLINT_IRON_CLAYMORE)
                .add(ArmoryItems.LAPIS_IRON_CLAYMORE)
                .add(ArmoryItems.QUARTZ_IRON_CLAYMORE)
                .add(ArmoryItems.GOLDEN_CLAYMORE)
                .add(ArmoryItems.FLINT_GOLDEN_CLAYMORE)
                .add(ArmoryItems.LAPIS_GOLDEN_CLAYMORE)
                .add(ArmoryItems.QUARTZ_GOLDEN_CLAYMORE)
                .add(ArmoryItems.DIAMOND_CLAYMORE)
                .add(ArmoryItems.FLINT_DIAMOND_CLAYMORE)
                .add(ArmoryItems.LAPIS_DIAMOND_CLAYMORE)
                .add(ArmoryItems.QUARTZ_DIAMOND_CLAYMORE)
                .add(ArmoryItems.NETHERITE_CLAYMORE)
                .add(ArmoryItems.FLINT_NETHERITE_CLAYMORE)
                .add(ArmoryItems.LAPIS_NETHERITE_CLAYMORE)
                .add(ArmoryItems.QUARTZ_NETHERITE_CLAYMORE);

        getOrCreateTagBuilder(ArmoryTags.Items.DAGGERS)
                .add(ArmoryItems.WOODEN_DAGGER)
                .add(ArmoryItems.STONE_DAGGER)
                .add(ArmoryItems.IRON_DAGGER)
                .add(ArmoryItems.GOLDEN_DAGGER)
                .add(ArmoryItems.DIAMOND_DAGGER)
                .add(ArmoryItems.NETHERITE_DAGGER)
                .add(ArmoryItems.FLINT_WOODEN_DAGGER)
                .add(ArmoryItems.LAPIS_WOODEN_DAGGER)
                .add(ArmoryItems.QUARTZ_WOODEN_DAGGER)
                .add(ArmoryItems.FLINT_STONE_DAGGER)
                .add(ArmoryItems.LAPIS_STONE_DAGGER)
                .add(ArmoryItems.QUARTZ_STONE_DAGGER)
                .add(ArmoryItems.FLINT_IRON_DAGGER)
                .add(ArmoryItems.LAPIS_IRON_DAGGER)
                .add(ArmoryItems.QUARTZ_IRON_DAGGER)
                .add(ArmoryItems.FLINT_GOLDEN_DAGGER)
                .add(ArmoryItems.LAPIS_GOLDEN_DAGGER)
                .add(ArmoryItems.QUARTZ_GOLDEN_DAGGER)
                .add(ArmoryItems.FLINT_DIAMOND_DAGGER)
                .add(ArmoryItems.LAPIS_DIAMOND_DAGGER)
                .add(ArmoryItems.QUARTZ_DIAMOND_DAGGER)
                .add(ArmoryItems.FLINT_NETHERITE_DAGGER)
                .add(ArmoryItems.LAPIS_NETHERITE_DAGGER)
                .add(ArmoryItems.QUARTZ_NETHERITE_DAGGER)
                .add(ArmoryItems.SPINDTOX);

    getOrCreateTagBuilder(ArmoryTags.Items.SWORDS)
            .add(Items.WOODEN_SWORD)
            .add(Items.STONE_SWORD)
            .add(Items.IRON_SWORD)
            .add(Items.GOLDEN_SWORD)
            .add(Items.DIAMOND_SWORD)
            .add(Items.NETHERITE_SWORD)
            .add(ArmoryItems.FLINT_WOODEN_SWORD)
            .add(ArmoryItems.FLINT_STONE_SWORD)
            .add(ArmoryItems.FLINT_IRON_SWORD)
            .add(ArmoryItems.FLINT_GOLDEN_SWORD)
            .add(ArmoryItems.FLINT_DIAMOND_SWORD)
            .add(ArmoryItems.FLINT_NETHERITE_SWORD)
            .add(ArmoryItems.LAPIS_WOODEN_SWORD)
            .add(ArmoryItems.LAPIS_STONE_SWORD)
            .add(ArmoryItems.LAPIS_IRON_SWORD)
            .add(ArmoryItems.LAPIS_GOLDEN_SWORD)
            .add(ArmoryItems.LAPIS_DIAMOND_SWORD)
            .add(ArmoryItems.LAPIS_NETHERITE_SWORD)
            .add(ArmoryItems.QUARTZ_WOODEN_SWORD)
            .add(ArmoryItems.QUARTZ_STONE_SWORD)
            .add(ArmoryItems.QUARTZ_IRON_SWORD)
            .add(ArmoryItems.QUARTZ_GOLDEN_SWORD)
            .add(ArmoryItems.QUARTZ_DIAMOND_SWORD)
            .add(ArmoryItems.QUARTZ_NETHERITE_SWORD)
            .addTag(ArmoryTags.Items.CLAYMORES)
            .addTag(ArmoryTags.Items.DAGGERS);

    getOrCreateTagBuilder(ArmoryTags.Items.PICKAXES)
            .add(Items.WOODEN_PICKAXE)
            .add(Items.STONE_PICKAXE)
            .add(Items.IRON_PICKAXE)
            .add(Items.GOLDEN_PICKAXE)
            .add(Items.DIAMOND_PICKAXE)
            .add(Items.NETHERITE_PICKAXE)
            .add(ArmoryItems.FLINT_WOODEN_PICKAXE)
            .add(ArmoryItems.FLINT_STONE_PICKAXE)
            .add(ArmoryItems.FLINT_IRON_PICKAXE)
            .add(ArmoryItems.FLINT_GOLDEN_PICKAXE)
            .add(ArmoryItems.FLINT_DIAMOND_PICKAXE)
            .add(ArmoryItems.FLINT_NETHERITE_PICKAXE)
            .add(ArmoryItems.LAPIS_WOODEN_PICKAXE)
            .add(ArmoryItems.LAPIS_STONE_PICKAXE)
            .add(ArmoryItems.LAPIS_IRON_PICKAXE)
            .add(ArmoryItems.LAPIS_GOLDEN_PICKAXE)
            .add(ArmoryItems.LAPIS_DIAMOND_PICKAXE)
            .add(ArmoryItems.LAPIS_NETHERITE_PICKAXE)
            .add(ArmoryItems.QUARTZ_WOODEN_PICKAXE)
            .add(ArmoryItems.QUARTZ_STONE_PICKAXE)
            .add(ArmoryItems.QUARTZ_IRON_PICKAXE)
            .add(ArmoryItems.QUARTZ_GOLDEN_PICKAXE)
            .add(ArmoryItems.QUARTZ_DIAMOND_PICKAXE)
            .add(ArmoryItems.QUARTZ_NETHERITE_PICKAXE);

        getOrCreateTagBuilder(ArmoryTags.Items.SINGLE_AXES)
                .add(Items.WOODEN_AXE)
                .add(Items.STONE_AXE)
                .add(Items.IRON_AXE)
                .add(Items.GOLDEN_AXE)
                .add(Items.DIAMOND_AXE)
                .add(Items.NETHERITE_AXE)
                .add(ArmoryItems.FLINT_WOODEN_AXE)
                .add(ArmoryItems.FLINT_STONE_AXE)
                .add(ArmoryItems.FLINT_IRON_AXE)
                .add(ArmoryItems.FLINT_GOLDEN_AXE)
                .add(ArmoryItems.FLINT_DIAMOND_AXE)
                .add(ArmoryItems.FLINT_NETHERITE_AXE)
                .add(ArmoryItems.LAPIS_WOODEN_AXE)
                .add(ArmoryItems.LAPIS_STONE_AXE)
                .add(ArmoryItems.LAPIS_IRON_AXE)
                .add(ArmoryItems.LAPIS_GOLDEN_AXE)
                .add(ArmoryItems.LAPIS_DIAMOND_AXE)
                .add(ArmoryItems.LAPIS_NETHERITE_AXE)
                .add(ArmoryItems.QUARTZ_WOODEN_AXE)
                .add(ArmoryItems.QUARTZ_STONE_AXE)
                .add(ArmoryItems.QUARTZ_IRON_AXE)
                .add(ArmoryItems.QUARTZ_GOLDEN_AXE)
                .add(ArmoryItems.QUARTZ_DIAMOND_AXE)
                .add(ArmoryItems.QUARTZ_NETHERITE_AXE);

        getOrCreateTagBuilder(ArmoryTags.Items.DOUBLE_AXES)
                .add(ArmoryItems.WOODEN_DOUBLE_AXE);

        getOrCreateTagBuilder(ArmoryTags.Items.SHOVELS)
                .add(Items.WOODEN_SHOVEL)
                .add(Items.STONE_SHOVEL)
                .add(Items.IRON_SHOVEL)
                .add(Items.GOLDEN_SHOVEL)
                .add(Items.DIAMOND_SHOVEL)
                .add(Items.NETHERITE_SHOVEL)
                .add(ArmoryItems.FLINT_WOODEN_SHOVEL)
                .add(ArmoryItems.FLINT_STONE_SHOVEL)
                .add(ArmoryItems.FLINT_IRON_SHOVEL)
                .add(ArmoryItems.FLINT_GOLDEN_SHOVEL)
                .add(ArmoryItems.FLINT_DIAMOND_SHOVEL)
                .add(ArmoryItems.FLINT_NETHERITE_SHOVEL)
                .add(ArmoryItems.LAPIS_WOODEN_SHOVEL)
                .add(ArmoryItems.LAPIS_STONE_SHOVEL)
                .add(ArmoryItems.LAPIS_IRON_SHOVEL)
                .add(ArmoryItems.LAPIS_GOLDEN_SHOVEL)
                .add(ArmoryItems.LAPIS_DIAMOND_SHOVEL)
                .add(ArmoryItems.LAPIS_NETHERITE_SHOVEL)
                .add(ArmoryItems.QUARTZ_WOODEN_SHOVEL)
                .add(ArmoryItems.QUARTZ_STONE_SHOVEL)
                .add(ArmoryItems.QUARTZ_IRON_SHOVEL)
                .add(ArmoryItems.QUARTZ_GOLDEN_SHOVEL)
                .add(ArmoryItems.QUARTZ_DIAMOND_SHOVEL)
                .add(ArmoryItems.QUARTZ_NETHERITE_SHOVEL);

        getOrCreateTagBuilder(ArmoryTags.Items.HOES)
                .add(Items.WOODEN_HOE)
                .add(Items.STONE_HOE)
                .add(Items.IRON_HOE)
                .add(Items.GOLDEN_HOE)
                .add(Items.DIAMOND_HOE)
                .add(Items.NETHERITE_HOE)
                .add(ArmoryItems.FLINT_WOODEN_HOE)
                .add(ArmoryItems.FLINT_STONE_HOE)
                .add(ArmoryItems.FLINT_IRON_HOE)
                .add(ArmoryItems.FLINT_GOLDEN_HOE)
                .add(ArmoryItems.FLINT_DIAMOND_HOE)
                .add(ArmoryItems.FLINT_NETHERITE_HOE)
                .add(ArmoryItems.LAPIS_WOODEN_HOE)
                .add(ArmoryItems.LAPIS_STONE_HOE)
                .add(ArmoryItems.LAPIS_IRON_HOE)
                .add(ArmoryItems.LAPIS_GOLDEN_HOE)
                .add(ArmoryItems.LAPIS_DIAMOND_HOE)
                .add(ArmoryItems.LAPIS_NETHERITE_HOE)
                .add(ArmoryItems.QUARTZ_WOODEN_HOE)
                .add(ArmoryItems.QUARTZ_STONE_HOE)
                .add(ArmoryItems.QUARTZ_IRON_HOE)
                .add(ArmoryItems.QUARTZ_GOLDEN_HOE)
                .add(ArmoryItems.QUARTZ_DIAMOND_HOE)
                .add(ArmoryItems.QUARTZ_NETHERITE_HOE);
    }
}
